Refactor: Formularios de contato e orcamento
Uperttech/uperttech-site pull request #7
Opened 2021-03-05 11:54 UTC by andersonsilva019

Nessa PR foi feito a mudança tanto do formulário de contato quanto de orçamentos para o layout da Uperttech. Foi removido o `<iframe/>` do google forms.

O código possui algumas partes com comentários das funcionalidades que não estão sendo utilizadas no momento, mas que serão utilizadas futuramente.

2021-03-05 13:13 UTC, llbarbosas commented on src/pages/_document.tsx
> +            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
Pra que serve esse import do font-awesome?

2021-03-05 13:14 UTC, llbarbosas requested changes
Pode remover todos os comentários das implementações antigas. Se precisarmos delas no futuro, podemos usar o histórico dos commits.

2021-03-05 13:26 UTC, andersonsilva019 commented on src/pages/_document.tsx
> +            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
É para aquele sinal de checked branco que aparece ao selecionar a opção de como conheceu a Uperttech no formulário de orçamento

2021-03-05 13:38 UTC, llbarbosas commented on src/pages/_document.tsx
> +            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
Ahh, achei
```ts
// src/components/Form/CheckBox/styles.ts
    &:after {
      font-family: 'Font Awesome 5 Free';
      font-weight: 900;
      content: '\f00c';
      font-size: 14px;
      color: #fff;
      display: none;
    }
```
Tinha estranhado porque nós já temos o react-icons no projeto, mas agora entendi. Ficou muito boa a solução só com CSS

2021-03-05 14:50 UTC, andersonsilva019 commented
Em relação do erro que estava no console(`Warning: Prop id did not match.`) encontrei essa solução no próprio repositório do react-select [aqui](https://github.com/JedWatson/react-select/issues/2629).

2021-03-07 23:43 UTC, llbarbosas requested changes
Corrigi alguns problemas com os checkboxes e adicionei o "Outro".

Os formulários estão redirecionando o usuário pra página de sucesso do Google Forms. Você vai precisar envia-los manualmente com um `preventDefault()` usando um `fetch` da vida para evitar isso. Você pode adicionar uma notificação de sucesso/erro no final de cada _submit_.

2021-03-08 14:29 UTC, andersonsilva019 commented
Utilizei como guia esse [post](https://blog.webjeda.com/google-form-customize/) na seção `Google Form Redirection` e para fazer o redirecionamento do usuário para a página principal foi utilizando o recurso do Next.

```ts
import { useRouter } from 'next/router'

const router = useRouter()
   ...
router.push(URL)
  ....
```

Como a lógica do redirecionamento seria a mesma para o formulário de contato e orçamento, separei essa lógica no `src/providers/AppProvider.tsx`.

```ts
const redirectSubmit = (message: string, url: string) => {
    try {
      toast.success(message)
      router.push(url).then(() => window.scrollTo(0, 0))
    } catch {
      dispatch({
        type: AppActionTypes.Error,
        payload: {
          error: 'Ocorreu um problema ao enviar, tente novamente !'
        }
      })
    }
  }
```

2021-03-14 14:45 UTC, llbarbosas requested changes

2021-03-14 14:45 UTC, llbarbosas commented on src/pages/index.tsx
> +    formData.append('entry.246867779', message)
Você não precisa fazer isso manualmente.  A API do `FormData` permite que você passe um elemento HTML `<form>`  na criação dele:

```js
function App() {
  const onSubmit = (ev) => {
    ev.preventDefault();

    const formData = new FormData(ev.target);

    // Você pode passar o FormData diretamente para a função fetch
    fetch(ev.target.action, {
      method: ev.target.method,
      body: formData
    }).then((d) => console.log(d));
    
    // Caso você precise manipular os dados do FormData, pode transformá-los num objeto
    const formDataObj = Array.from(formData.entries()).reduce(
      (acc, [k, v]) => ({ ...acc, [k]: v }),
      {}
    );
    
     // Saída: {name: "Nome", email: "E-mail", password: "123456"}
    console.log(formDataObj);
  };

  return (
    <div className="App">
      <form onSubmit={onSubmit} action="/signin" method="POST">
        <input type="text" name="name" />
        <input type="text" name="email" />
        <input type="password" name="password" />
        <button type="submit">Submit</button>
      </form>
    </div>
  );
}
```

2021-03-14 14:45 UTC, llbarbosas commented on src/pages/orcamento.tsx
> +    formData.append('entry.1651142815', budgetValue.value)
Veja o comentário do `src/pages/index.tsx`

2021-03-14 14:45 UTC, llbarbosas commented on src/providers/AppProvider.tsx
> +  const router = useRouter()
Navegação é uma responsabilidade das páginas. Se você quer que a navegação mude depois do envio, você deve fazer isso na página que chamou o `sendContact`/`sendBudget`:

```ts
// src/pages/orcamento.tsx

const handleSubmit = async (event: FormEvent) => {
    event.preventDefault()
    
    const formData = new FormData(ev.target)

    await sendBudget('Seu orçamento foi enviado com sucesso !', '/', formData)

    if (!loading && !error) {
        router.push(url).then(() => window.scrollTo(0, 0))
    }
  }
```

2021-03-14 14:45 UTC, llbarbosas commented on src/providers/AppProvider.tsx
> +          error: 'Não foi possível enviar sua menssagem, tente novamente!'
```ts
error: 'Não foi possível enviar sua mensagem, tente novamente'
```

2021-03-14 14:45 UTC, llbarbosas commented on src/util/API-FORM.ts
> +    await fetch(
O `fetch` só dispara erros de conexão. Você precisa disparar os erros `4xx`/`5xx` manualmente:

```ts
fetch(url).then((response) => {
  if (!response.ok) {
    throw new Error(response.status)
  }
})
```

2021-03-15 11:49 UTC, andersonsilva019 commented on src/pages/index.tsx
> +    formData.append('entry.246867779', message)
Poderia ser dessa forma ?

```ts
// src/pages/index.tsx
function App() {
  const onSubmit = (ev: FormEvent) => {
    ev.preventDefault();

    const formData = new FormData(ev.target as HTMLFormElement);

    sendContact(formData)
    if (!loading && !error) {
      toast.success('Sua mensagem foi enviada com sucesso !')
      router.push('/').then(() => window.scrollTo(0, 0))
    }
    setDataForm({ name: '', email: '', message: '' })
  
  };

  return (
    <div className="App">
      <form onSubmit={onSubmit} action="/signin" method="POST">
        <input type="text" name="name" />
        <input type="text" name="email" />
        <input type="password" name="password" />
        <button type="submit">Submit</button>
      </form>
    </div>
  );
}
```

2021-03-15 12:00 UTC, llbarbosas commented on src/pages/index.tsx
> +    formData.append('entry.246867779', message)
Sim, com algumas mudanças:

```ts
// src/pages/index.tsx
function App() {
  const onSubmit = (ev: FormEvent) => {
    ev.preventDefault();

    const formData = new FormData(ev.target as HTMLFormElement);

    // await para aguardar o envio do formulário
    await sendContact(formData)

    if (!loading && !error) {
      // Limpando o form somente no caso de sucesso
      setDataForm({ name: '', email: '', message: '' })
      // Lembrando de padronizar a escrita das mensagens
      toast.success('Sua mensagem foi enviada com sucesso')
      router.push('/').then(() => window.scrollTo(0, 0))
    }
  
  };

  return (
    <div className="App">
      <form onSubmit={onSubmit} action="/signin" method="POST">
        <input type="text" name="name" />
        <input type="text" name="email" />
        <input type="password" name="password" />
        <button type="submit">Submit</button>
      </form>
    </div>
  );
}
```

2021-03-15 12:07 UTC, andersonsilva019 commented on src/pages/index.tsx
> +    formData.append('entry.246867779', message)
```ts
// src/util/API.FORM.ts
sendContact: async (data: FormData): Promise<void> => {
    const response = await fetch(
      'https://docs.google.com/forms/u/0/d/e/1FAIpQLSdGQNmUGUbGXgPQAAqIAbxj6JYeLo0ca8ScL5TO0-XiJBgSPw/formResponse',
      {
        method: 'POST',
        mode: 'no-cors',
        body: data
      }
    )

    if (!response.ok) {
      throw new Error(response.statusText)
    }
  },
```

2021-03-15 12:08 UTC, andersonsilva019 commented on src/pages/index.tsx
> +    formData.append('entry.246867779', message)
```ts
// src/providers/AppProvider.tsx
const sendContact = async (data: FormData) => {
    try {
      dispatch({ type: AppActionTypes.Start })
      await API.sendContact(data)
      dispatch({ type: AppActionTypes.Success })
    } catch {
      dispatch({
        type: AppActionTypes.Error,
        payload: {
          error: 'Não foi possível enviar sua mensagem, tente novamente'
        }
      })
    }
  }
```

2021-03-15 12:40 UTC, llbarbosas commented on src/pages/index.tsx
> +    formData.append('entry.246867779', message)
> // src/providers/AppProvider.tsx
> const sendContact = async (data: FormData) => {

O toastify não ficaria no aqui?

2021-03-15 12:49 UTC, andersonsilva019 commented on src/pages/index.tsx
> +    formData.append('entry.246867779', message)
Vou colocar o toastify no provider. Eu achei que ficaria melhor na página.

2021-03-15 13:36 UTC, llbarbosas commented on src/pages/index.tsx
> +    formData.append('entry.246867779', message)
> O que acha do toast ficar na página?

Olha, nesse caso acho que tudo bem, já que cada funcionalidade só vai ser usada na própria página. Mas quando você coloca uma funcionalidade num provider, espera-se que ela possa ser utilizada em outros lugares. Como a notificação tá vinculada com a mudança de estado, ela acabaria indo pro provider.

2021-03-15 13:58 UTC, andersonsilva019 commented on src/pages/index.tsx
> +    formData.append('entry.246867779', message)
Entendi. Então vou adicionar o toast no provider mesmo.

2021-03-16 14:02 UTC, andersonsilva019 commented
Tudo certo ?

2021-03-22 14:23 UTC, llbarbosas approved these changes

2021-03-22 14:24 UTC, merged